import numpy as np

from scipy.linalg import sqrtm, solve_lyapunov
from geomstats.geometry.spd_matrices import SPDMatrices, SPDBuresWassersteinMetric


def make_rotation_2d(angle):
    # Returns 2d matrix rotation from angle. Vectorized.
    if np.array(angle).ndim == 1:
        return np.stack([
            np.array([[np.cos(a), -np.sin(a)], [np.sin(a), np.cos(a)]])
            for a in np.array(angle)
        ])
    return np.array([[np.cos(angle), -np.sin(angle)], [np.sin(angle), np.cos(angle)]])


def points_from_angles_2d(angles, sq_roots):
    rotations = make_rotation_2d(angles)
    return sq_roots @ rotations


def project(mat):
    # Project matrix of GL(n) into SPD(n). Vectorized.
    if mat.ndim == 3:
        return np.stack([m @ m.T for m in mat])
    return mat @ mat.T


def tangent_project(vec, mat):
    # Differential of projection
    return vec @ mat.T + mat @ vec.T


def monge_map(cov_a, cov_b):
    # Compute the only symmetric positive definite
    # matrix T such that T @ cov_a @ T^t = cov_b.
    return np.linalg.inv(cov_a) @ sqrtm(cov_a @ cov_b)


def align_unit(cov, ref_mat):
    # Find the element of the fiber over cov (matrix in GL(n))
    # that is closest to ref_mat.
    ref_cov = project(ref_mat)
    monge_mat = monge_map(ref_cov, cov)
    return monge_mat @ ref_mat


def align(cov, ref_mat):
    # Find the element of the fiber over cov (matrix in GL(n))
    # that is closest to ref_mat. Vectorized.
    if cov.ndim == 3:
        return np.stack([align_unit(m, ref_mat) for m in cov])
    return align_unit(cov, ref_mat)


def bures_wasserstein_sectional_curvature(vec_1, vec_2, base_point):
    # Compute sectional curvature of the plane generated by vec_1
    # and vec_2 at base_point.
    dim = base_point.shape[0]
    spd_space = SPDMatrices(dim)
    spd_space.equip_with_metric(SPDBuresWassersteinMetric)
    d, P = np.linalg.eigh(base_point)
    vec_1_0 = solve_lyapunov(base_point, vec_1)
    vec_2_0 = solve_lyapunov(base_point, vec_2)
    assert np.all(np.abs(base_point @ vec_1_0 + vec_1_0 @ base_point - vec_1) < 1e-6)
    assert np.all(np.abs(base_point @ vec_2_0 + vec_2_0 @ base_point - vec_2) < 1e-6)
    vec_1_0_prime = P.T @ vec_1_0 @ P
    vec_2_0_prime = P.T @ vec_2_0 @ P
    bracket = vec_1_0_prime @ vec_2_0_prime - vec_2_0_prime @ vec_1_0_prime
    dl, dc = np.meshgrid(d, d)
    coef = dl * dc / (dl + dc)
    num = 3/2 * np.sum(coef * bracket ** 2)
    den = (
        spd_space.metric.norm(vec_1, base_point) ** 2 * spd_space.metric.norm(vec_2, base_point) ** 2 -
        spd_space.metric.inner_product(vec_1, vec_2, base_point) ** 2
    )
    return num / den


def bures_wasserstein_ricci_curvature_unit(vec, base_point):
    dim = base_point.shape[0]
    spd_space = SPDMatrices(dim)
    spd_space.equip_with_metric(SPDBuresWassersteinMetric)
    ricci = 0.
    for i in range(dim):
        for j in range(i, dim):
            basis_vec_ij = np.zeros((dim, dim))
            basis_vec_ij[i, j] = 1.
            basis_vec_ij[j, i] = 1.
            ricci += bures_wasserstein_sectional_curvature(basis_vec_ij, vec, base_point)
    return ricci


def bures_wasserstein_ricci_curvature(vec, base_point):
    if vec.ndim == 3:
        ricci = []
        for (vc, bp) in zip(vec, base_point):
            ricci.append(bures_wasserstein_ricci_curvature_unit(vc, bp))
        return np.array(ricci)
    return bures_wasserstein_ricci_curvature_unit(vec, base_point)
